//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OPSMessages.WSGestionarBonosGiropark {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bonosBinding", Namespace="urn:bonos")]
    public partial class bonos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExisteBonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTiempoBonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UsarBonoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public bonos() {
            this.Url = global::OPSMessages.Properties.Settings.Default.OPS_Messages_1_2_1_1_WSGestionarBonosGiropark_bonos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExisteBonoCompletedEventHandler ExisteBonoCompleted;
        
        /// <remarks/>
        public event ObtenerTiempoBonoCompletedEventHandler ObtenerTiempoBonoCompleted;
        
        /// <remarks/>
        public event UsarBonoCompletedEventHandler UsarBonoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:bonos#ExisteBono", RequestNamespace="urn:bonos", ResponseNamespace="urn:bonos")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int ExisteBono(int CodigoPoblacion, string Bono, string FechaParquimetro) {
            object[] results = this.Invoke("ExisteBono", new object[] {
                        CodigoPoblacion,
                        Bono,
                        FechaParquimetro});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExisteBono(int CodigoPoblacion, string Bono, string FechaParquimetro, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExisteBono", new object[] {
                        CodigoPoblacion,
                        Bono,
                        FechaParquimetro}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndExisteBono(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteBonoAsync(int CodigoPoblacion, string Bono, string FechaParquimetro) {
            this.ExisteBonoAsync(CodigoPoblacion, Bono, FechaParquimetro, null);
        }
        
        /// <remarks/>
        public void ExisteBonoAsync(int CodigoPoblacion, string Bono, string FechaParquimetro, object userState) {
            if ((this.ExisteBonoOperationCompleted == null)) {
                this.ExisteBonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteBonoOperationCompleted);
            }
            this.InvokeAsync("ExisteBono", new object[] {
                        CodigoPoblacion,
                        Bono,
                        FechaParquimetro}, this.ExisteBonoOperationCompleted, userState);
        }
        
        private void OnExisteBonoOperationCompleted(object arg) {
            if ((this.ExisteBonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteBonoCompleted(this, new ExisteBonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:bonos#ObtenerTiempoBono", RequestNamespace="urn:bonos", ResponseNamespace="urn:bonos")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int ObtenerTiempoBono(int CodigoPoblacion, long Bono, string FechaParquimetro) {
            object[] results = this.Invoke("ObtenerTiempoBono", new object[] {
                        CodigoPoblacion,
                        Bono,
                        FechaParquimetro});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerTiempoBono(int CodigoPoblacion, long Bono, string FechaParquimetro, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerTiempoBono", new object[] {
                        CodigoPoblacion,
                        Bono,
                        FechaParquimetro}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndObtenerTiempoBono(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTiempoBonoAsync(int CodigoPoblacion, long Bono, string FechaParquimetro) {
            this.ObtenerTiempoBonoAsync(CodigoPoblacion, Bono, FechaParquimetro, null);
        }
        
        /// <remarks/>
        public void ObtenerTiempoBonoAsync(int CodigoPoblacion, long Bono, string FechaParquimetro, object userState) {
            if ((this.ObtenerTiempoBonoOperationCompleted == null)) {
                this.ObtenerTiempoBonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTiempoBonoOperationCompleted);
            }
            this.InvokeAsync("ObtenerTiempoBono", new object[] {
                        CodigoPoblacion,
                        Bono,
                        FechaParquimetro}, this.ObtenerTiempoBonoOperationCompleted, userState);
        }
        
        private void OnObtenerTiempoBonoOperationCompleted(object arg) {
            if ((this.ObtenerTiempoBonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTiempoBonoCompleted(this, new ObtenerTiempoBonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:bonos#UsarBono", RequestNamespace="urn:bonos", ResponseNamespace="urn:bonos")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int UsarBono(int CodigoPoblacion, int Importe, long Bono, string FechaPago, int NumeroParquimetro, int NumeroOperacion) {
            object[] results = this.Invoke("UsarBono", new object[] {
                        CodigoPoblacion,
                        Importe,
                        Bono,
                        FechaPago,
                        NumeroParquimetro,
                        NumeroOperacion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUsarBono(int CodigoPoblacion, int Importe, long Bono, string FechaPago, int NumeroParquimetro, int NumeroOperacion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UsarBono", new object[] {
                        CodigoPoblacion,
                        Importe,
                        Bono,
                        FechaPago,
                        NumeroParquimetro,
                        NumeroOperacion}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUsarBono(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UsarBonoAsync(int CodigoPoblacion, int Importe, long Bono, string FechaPago, int NumeroParquimetro, int NumeroOperacion) {
            this.UsarBonoAsync(CodigoPoblacion, Importe, Bono, FechaPago, NumeroParquimetro, NumeroOperacion, null);
        }
        
        /// <remarks/>
        public void UsarBonoAsync(int CodigoPoblacion, int Importe, long Bono, string FechaPago, int NumeroParquimetro, int NumeroOperacion, object userState) {
            if ((this.UsarBonoOperationCompleted == null)) {
                this.UsarBonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsarBonoOperationCompleted);
            }
            this.InvokeAsync("UsarBono", new object[] {
                        CodigoPoblacion,
                        Importe,
                        Bono,
                        FechaPago,
                        NumeroParquimetro,
                        NumeroOperacion}, this.UsarBonoOperationCompleted, userState);
        }
        
        private void OnUsarBonoOperationCompleted(object arg) {
            if ((this.UsarBonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsarBonoCompleted(this, new UsarBonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ExisteBonoCompletedEventHandler(object sender, ExisteBonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteBonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteBonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ObtenerTiempoBonoCompletedEventHandler(object sender, ObtenerTiempoBonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTiempoBonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTiempoBonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void UsarBonoCompletedEventHandler(object sender, UsarBonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UsarBonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UsarBonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591