//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSMessages.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gesblue.com/admin/webservice_bonos.php")]
        public string OPS_Messages_1_2_1_1_WSGestionarBonosGiropark_bonos {
            get {
                return ((string)(this["OPS_Messages_1_2_1_1_WSGestionarBonosGiropark_bonos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://95.177.110.177:3381/WSOPS2NEWPARK.asmx")]
        public string OPS_Messages_1_2_1_1_WSNewPark_WSOPS2NewPark {
            get {
                return ((string)(this["OPS_Messages_1_2_1_1_WSNewPark_WSOPS2NewPark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://esdcvyewb00p.eysa.local/parquimetrosws/framework/anulaciones.asmx")]
        public string OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionEYSA_Donostia_Anulaciones {
            get {
                return ((string)(this["OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionEYSA_Donostia_Anulaciones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gesblue.com/admin/webservice_anulaciones.php")]
        public string OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionGiropark_anulaciones {
            get {
                return ((string)(this["OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionGiropark_anulaciones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://77.226.247.202/SETEX/SETEX_ConsultaExpediente.asmx")]
        public string OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionSETEX_Castrourdiales_SETEX {
            get {
                return ((string)(this["OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionSETEX_Castrourdiales_SETEX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://77.226.247.202/SETEX/SETEX_ConsultaExpediente.asmx")]
        public string OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionSETEX_Cordoba_SETEX {
            get {
                return ((string)(this["OPS_Messages_1_2_1_1_WSObtenerImporteAnulacionSETEX_Cordoba_SETEX"]));
            }
        }
    }
}
